if(!window.curriculumData) window.curriculumData = {};
window.curriculumData.en_a1 = [
{
  id:'u0', num:0, color:'#10B981', label:'Unit 0: First Steps (A0)',
  arc:'Greetings → The Alphabet → Numbers 1-20 → Basic Pronunciation',
  lessons_count:5,
  lessons:[
    { code:'A1-001', num:1, title:'Hello & Welcome',
      grammar:'Verb "to be" (am/is/are) — positive forms',
      pronunciation: [
        {
          point: "The English Alphabet",
          explain: "English has 26 letters but many more sounds. Start with the names of the letters.",
          alphabet: [
            {l:'A', ipa:'/eɪ/'}, {l:'B', ipa:'/biː/'}, {l:'C', ipa:'/siː/'}, {l:'D', ipa:'/diː/'}, {l:'E', ipa:'/iː/'},
            {l:'F', ipa:'/ef/'}, {l:'G', ipa:'/dʒiː/'}, {l:'H', ipa:'/eɪtʃ/'}, {l:'I', ipa:'/aɪ/'}, {l:'J', ipa:'/dʒeɪ/'},
            {l:'K', ipa:'/keɪ/'}, {l:'L', ipa:'/el/'}, {l:'M', ipa:'/em/'}, {l:'N', ipa:'/en/'}, {l:'O', ipa:'/əʊ/'},
            {l:'P', ipa:'/piː/'}, {l:'Q', ipa:'/kjuː/'}, {l:'R', ipa:'/ɑː/'}, {l:'S', ipa:'/es/'}, {l:'T', ipa:'/tiː/'},
            {l:'U', ipa:'/juː/'}, {l:'V', ipa:'/viː/'}, {l:'W', ipa:'/ˈdʌb.əl.juː/'}, {l:'X', ipa:'/eks/'}, {l:'Y', ipa:'/waɪ/'}, {l:'Z', ipa:'/zed/'}
          ],
          extension: "Did you know? The letters A, E, I, O, U are vowels. All other letters are consonants. In English, one letter can often represent multiple different sounds!",
          visual: "🔤"
        }
      ],
      vocab: ['Hello', 'Hi', 'Good morning', 'Good afternoon', 'Good evening', 'Goodbye'],
      cando:'Can greet people and say goodbye',
      hw:'Learn the alphabet song' },
    { code:'A1-002', num:2, title:'What is your name?',
      grammar:'Verb "to be" — questions (What is...?)',
      pronunciation: [
        {
          point: "Contractions",
          explain: "In spoken English, we often combine words. 'What is' becomes 'What's'.",
          examples: [
            { pattern: "What is", ipa: "/wɒt ɪz/", word: "What's" },
            { pattern: "I am", ipa: "/aɪ æm/", word: "I'm" },
            { pattern: "My name is", ipa: "/maɪ neɪm ɪz/", word: "My name's" }
          ],
          extension: "Contractions make your English sound more natural and fluent. We use them almost all the time when speaking!",
          visual: "🔗"
        }
      ],
      vocab: ['Name', 'What', 'How', 'Nice to meet you'],
      cando:'Can introduce themselves',
      hw:'Practice spelling your name' },
    { code:'A1-003', num:3, title:'Numbers 1-20',
      grammar:'Singular and Plural nouns (intro)',
      pronunciation: [
        {
          point: "Numbers -teen vs -ty",
          explain: "Stress is key to distinguish numbers like 13 and 30.",
          examples: [
            { pattern: "13", ipa: "/ˌθɜːˈtiːn/", word: "thirteen" },
            { pattern: "30", ipa: "/ˈθɜː.ti/", word: "thirty" }
          ]
        }
      ],
      vocab: ['one', 'two', 'three', 'ten', 'twenty'],
      cando:'Can count from 1 to 20',
      hw:'Count objects in your room' },
    { code:'A1-004', num:4, title:'Minimal Pairs 1: Vowels',
      grammar:'Basic sentence structure',
      pronunciation: [
        {
          point: "Short vs Long Vowels",
          explain: "Short sounds vs long sounds can change the meaning of a word.",
          minimalPairs: [
            { w1: "ship", p1: "/ʃɪp/", w2: "sheep", p2: "/ʃiːp/" },
            { w1: "bit", p1: "/bɪt/", w2: "beat", p2: "/biːt/" },
            { w1: "fit", p1: "/fɪt/", w2: "feet", p2: "/fiːt/" }
          ],
          extension: "The length of the vowel is very important in English. Notice how your mouth stays in a similar position but the sound lasts longer for 'sheep' and 'beat'.",
          visual: "🚢↔️🐑"
        }
      ],
      vocab: ['ship', 'sheep', 'feet', 'sit'],
      cando:'Can distinguish between short and long vowel sounds',
      hw:'Record yourself saying ship and sheep' },
    { code:'A1-005', num:5, title:'Essential Phrases',
      grammar:'Polite requests (Please, Thank you)',
      pronunciation: [
        {
          point: "Word Stress",
          explain: "The most important part of the word is louder and longer.",
          examples: [
            { pattern: "Please", ipa: "/pliːz/", word: "please" },
            { pattern: "Thank you", ipa: "/ˈθæŋk.juː/", word: "thank you" },
            { pattern: "Excuse me", ipa: "/ɪkˈskjuːz.miː/", word: "excuse me" }
          ]
        }
      ],
      vocab: ['Please', 'Thank you', 'Excuse me', 'Sorry'],
      cando:'Can use basic polite phrases',
      hw:'Use three polite phrases tomorrow' }
  ]
},
{
  id:'u1', num:1, color:'#3B82F6', label:'My Life Today',
  arc:'Daily routines → Work → Home → Money → Food → Tech → Free time → Community',
  lessons_count:10,
  grammar_summary:[
    {name:'Present Simple (all forms)', desc:'Full paradigm with frequency adverbs', ex:'"She usually works from home."', ref:'present-simple'},
    {name:'Should / Shouldn\'t', desc:'Advice in health and daily life', ex:'"You should eat more vegetables."', ref:'modals'},
    {name:'Have to / Don\'t have to', desc:'Obligation and lack of obligation', ex:'"I have to pay rent by Friday."', ref:'modals'},
    {name:'Like / Love / Hate + -ing', desc:'Gradable opinion scale with gerund', ex:'"I really enjoy cooking at weekends."', ref:'present-simple'},
    {name:'Comparatives (review)', desc:'Extended review of basic comparisons', ex:'"My commute is longer than before."', ref:'grammar-reference.html'},
  ],
  vocab_themes:['Work Basics','Home & Housing','Daily Routine','Health Basics','Money & Shopping','Technology','Leisure & Social Life'],
  lessons:[
    { code:'A1-01', num:1, title:'A day in my life — routines revisited',
      grammar:'Present simple: all persons + frequency adverbs (mid-position)',
      pronunciation: [
        {
          point: "Starter Foundation: The Alphabet Sounds",
          explain: "Master the vowel sounds in the alphabet which often cause confusion.",
          examples: [
            { pattern: "A, H, J, K", ipa: "/eɪ/", word: "Alphabet" },
            { pattern: "E, B, C, D, G, P, T, V", ipa: "/iː/", word: "Email" },
            { pattern: "I, Y", ipa: "/aɪ/", word: "Identity" }
          ],
          tip: "English vowels 'A' and 'E' are often swapped by learners from other languages!"
        },
        {
          point: "The Schwa Sound /ə/",
          explain: "The most common sound in English. It's short, weak, and found in unstressed syllables.",
          examples: [
            { pattern: "a", ipa: "/ə'baʊt/", word: "about" },
            { pattern: "er", ipa: "/'tiːtʃə/", word: "teacher" },
            { pattern: "o", ipa: "/'pəʊlɪs/", word: "police" }
          ],
          tip: "Relax your mouth completely to make this sound."
        }
      ],
      vocab: ['always', 'usually', 'often', 'sometimes', 'rarely', 'never', 'wake up', 'get up', 'leave', 'arrive', 'finish'],
      verbs:['wake up','get up','leave','arrive','start','finish'],
      adj:[],
      speaking:'Compare routines with 2 partners using frequency adverbs',
      listening:'Extended daily routine (3 speakers)',
      reading:'A "day in the life" magazine article',
      writing:'Full daily routine paragraph (8 sentences + frequency)',
      task:'Class routine survey: who does what, how often?',
      cando:'Can describe daily routines using all frequency adverbs',
      hw:'Write a detailed weekly routine with frequency adverbs' },
    { code:'A1-02', num:2, title:'My job — describing work in detail',
      grammar:'Present simple: "I work with/for/in; I am responsible for…"',
      pronunciation: [
        {
          point: "Word Stress in Occupations",
          explain: "Multi-syllable words always have one syllable that is stronger than the others.",
          examples: [
            { pattern: "oo", ipa: "/ˌen.dʒɪˈnɪər/", word: "engineer" },
            { pattern: "o", ipa: "/ˈfəʊ.tə.ɡrɑː.fər/", word: "photographer" },
            { pattern: "a", ipa: "/ˈmæn.ɪ.dʒər/", word: "manager" }
          ],
          tip: "Tap your finger on the desk for the stressed syllable."
        }
      ],
      vocab: ['job', 'work', 'boss', 'colleague', 'salary', 'office', 'meeting', 'email', 'full-time', 'part-time'],
      verbs:['manage','attend','check','send','meet','reply','help','order','visit'],
      adj:['busy'],
      speaking:'Describe your job in 5 sentences to a partner',
      listening:'3 job descriptions from real professionals',
      reading:'A short job description from a job advert',
      writing:'Job description for your own role (6 sentences)',
      task:'Job description swap: guess the job from description',
      cando:'Can describe what their job involves using present simple',
      hw:'Write a job description as if for a LinkedIn profile' },
    { code:'A1-03', num:3, title:'My commute and workplace',
      grammar:'"How long does it take? / How far is it?" + It takes / It is',
      pronunciation: [
        {
          point: "The /θ/ and /ð/ Sounds",
          explain: "English 'th' has two sounds: unvoiced /θ/ (think) and voiced /ð/ (the).",
          examples: [
            { pattern: "th", ipa: "/θɪŋk/", word: "think" },
            { pattern: "th", ipa: "/ðə/", word: "the" },
            { pattern: "th", ipa: "/'ɜː.θɪŋ/", word: "earth" }
          ],
          tip: "Put your tongue between your teeth and blow."
        }
      ],
      vocab: ['commute', 'floor', 'department', 'delay', 'rush hour'],
      verbs:['travel','leave','arrive'],
      adj:['busy','free','difficult'],
      speaking:'Tell a partner about your commute in detail',
      listening:'Two people discussing their commutes',
      reading:'Short article on commuting in cities',
      writing:'Paragraph about your commute and workplace',
      task:'Commute debate: which is the best way to travel?',
      cando:'Can discuss commute and workplace location',
      hw:'Write a 60-word commute description' },
    { code:'A1-04', num:4, title:'Earning and spending — money vocabulary',
      grammar:'How much do you earn/spend? Present simple + object; too + adjective / enough',
      pronunciation: [
        {
          point: "Numbers and Word Stress",
          explain: "Differentiate between -teen and -ty numbers using stress.",
          examples: [
            { pattern: "teen", ipa: "/ˌθɜːˈtiːn/", word: "thirteen" },
            { pattern: "ty", ipa: "/ˈθɜː.ti/", word: "thirty" },
            { pattern: "teen", ipa: "/ˌfɔːˈtiːn/", word: "fourteen" }
          ],
          tip: "The '-teen' is long and high; the '-ty' is short and low."
        }
      ],
      vocab: ['spend', 'save', 'pay', 'cost', 'cash', 'card', 'receipt', 'discount', 'bill'],
      verbs:['earn','afford','charge','pay','spend','save'],
      adj:['cheap','expensive'],
      speaking:'Discuss spending habits: what do you spend most on?',
      listening:'People discussing financial habits',
      reading:'Short article on managing money',
      writing:'Monthly budget plan in full sentences',
      task:'Budget challenge: live on €1,500/month (group task)',
      cando:'Can discuss earning and spending habits',
      hw:'Write a paragraph about your financial habits' },
    { code:'A1-05', num:5, title:'My home — renting and buying',
      grammar:'Have to / don\'t have to (obligation intro); How much does it cost?',
      pronunciation: [
        {
          point: "Vowel Sound /eɪ/ (Long A)",
          explain: "Common in words like 'name' and 'station'. It's a diphthong (two sounds in one).",
          examples: [
            { pattern: "a_e", ipa: "/neɪm/", word: "name" },
            { pattern: "ai", ipa: "/peɪ/", word: "pay" },
            { pattern: "ay", ipa: "/deɪ/", word: "day" }
          ],
          tip: "Open your mouth then move your jaw up slightly."
        }
      ],
      vocab: ['rent', 'flat', 'landlord', 'tenant', 'neighbour', 'furniture', 'heating', 'bill'],
      verbs:['rent','move','repair','clean','cook'],
      adj:['cheap','expensive','different'],
      speaking:'Role-play: tenant phones landlord about a flat',
      listening:'A rental enquiry phone call',
      reading:'A property advert',
      writing:'Email to a landlord asking about a flat',
      task:'Flat hunting: compare two properties and decide',
      cando:'Can ask about and describe a rental property',
      hw:'Write a short email enquiry about a flat to rent' },
    { code:'A1-06', num:6, title:'Food and health — what you eat, how you feel',
      grammar:'Should / shouldn\'t for advice: "You should eat more… / You shouldn\'t…"',
      pronunciation: [
        {
          point: "The /i:/ and /ɪ/ Sounds",
          explain: "Differentiate between long 'ee' (feel) and short 'i' (ill).",
          examples: [
            { pattern: "ee", ipa: "/fiːl/", word: "feel" },
            { pattern: "i", ipa: "/ɪl/", word: "ill" },
            { pattern: "ea", ipa: "/iːt/", word: "eat" }
          ],
          tip: "Think of a 'smile' for the long /i:/ sound."
        }
      ],
      vocab: ['ill', 'tired', 'headache', 'doctor', 'hospital', 'medicine', 'sleep', 'exercise', 'stress'],
      verbs:['feel','rest','recover','exercise','hurt'],
      adj:['healthy','ill','fit','tired','stressed'],
      speaking:'Give a partner 3 pieces of health advice',
      listening:'A nutritionist giving advice',
      reading:'A healthy eating guide',
      writing:'5 health advice sentences using should/shouldn\'t',
      task:'Health clinic: one person describes habits, partner gives advice',
      cando:'Can give and receive basic health advice using should',
      hw:'Write a 5-tip healthy lifestyle guide' },
    { code:'A1-07', num:7, title:'Technology in my life',
      grammar:'Present simple + adverbs of frequency + like + -ing for tech habits',
      pronunciation: [
        {
          point: "Silent 'e' in Tech Words",
          explain: "The final 'e' is often silent but changes the previous vowel sound.",
          examples: [
            { pattern: "_one", ipa: "/fəʊn/", word: "phone" },
            { pattern: "_ine", ipa: "/'ɒn.laɪn/", word: "online" },
            { pattern: "een", ipa: "/skriːn/", word: "screen" }
          ],
          tip: "The vowel before the consonant becomes 'long' because of the magic 'e'."
        }
      ],
      vocab: ['phone', 'app', 'password', 'internet', 'online', 'screen'],
      verbs:['check','send','watch','follow','learn'],
      adj:['online','free','popular'],
      speaking:'Discuss your technology habits with a partner',
      listening:'People describing tech habits',
      reading:'A short survey on technology use',
      writing:'A paragraph about your technology use',
      task:'Tech debate: is your phone your best friend?',
      cando:'Can describe technology habits using present simple',
      hw:'Write: "How I use technology every day"' },
    { code:'A1-08', num:8, title:'My interests and free time',
      grammar:'Love / like / enjoy / don\'t mind / hate / can\'t stand + -ing (gradable scale)',
      pronunciation: [
        {
          point: "The /-ing/ Ending /ŋ/",
          explain: "The 'g' is not fully pronounced. It's a nasal sound made at the back of the throat.",
          examples: [
            { pattern: "ing", ipa: "/ˈpleɪ.ɪŋ/", word: "playing" },
            { pattern: "ing", ipa: "/ˈrɪː.dɪŋ/", word: "reading" },
            { pattern: "ing", ipa: "/ˈkʊk.ɪŋ/", word: "cooking" }
          ],
          tip: "Keep the back of your tongue up against the roof of your mouth."
        }
      ],
      vocab: ['holiday', 'weekend', 'free time', 'friend', 'invitation', 'party', 'hobby'],
      verbs:['relax','enjoy','invite','celebrate','play'],
      adj:['happy','relaxed','bored','excited','free'],
      speaking:'Discuss free time preferences using the full scale',
      listening:'A leisure preferences survey',
      reading:'A "My free time" blog entry',
      writing:'"My interests" paragraph (6–8 sentences)',
      task:'Interest match: find someone with the same top hobby',
      cando:'Can express interests with gradable opinion verbs',
      hw:'Write a short paragraph about your ideal weekend' },
    { code:'A1-09', num:9, title:'My neighbourhood and community',
      grammar:'There is/are + quantity; adjectives for opinions; comparatives review',
      pronunciation: [
        {
          point: "The /v/ and /b/ Sounds",
          explain: "Many learners confuse these. /v/ is a 'fricative' (vibration), /b/ is a 'plosive' (stop).",
          examples: [
            { pattern: "v", ipa: "/'vɪl.ɪdʒ/", word: "village" },
            { pattern: "v", ipa: "/'veɹ.i/", word: "very" },
            { pattern: "b", ipa: "/'bɪl.dɪŋ/", word: "building" }
          ],
          tip: "For /v/, your top teeth should touch your bottom lip."
        }
      ],
      vocab: ['neighbour', 'local', 'convenient', 'community'],
      verbs:['live','move','seem','happen'],
      adj:['quiet','noisy','convenient','popular','special','different','similar'],
      speaking:'Describe your neighbourhood to a partner',
      listening:'Two people comparing neighbourhoods',
      reading:'A "Where I live" blog post',
      writing:'Neighbourhood description (6 sentences)',
      task:'My ideal neighbourhood: design and present',
      cando:'Can describe and evaluate a neighbourhood',
      hw:'Write a "Where I live" paragraph' },
    { code:'A1-10', num:10, title:'Unit 1 Review — My life today',
      grammar:'Present simple (all forms) + should + have to + frequency + like -ing',
      vocab: ['ALL Unit 1 vocabulary'],
      verbs:['ALL Unit 1 verbs'],
      adj:['ALL Unit 1 adjectives'],
      speaking:'Oral: describe your life today (3 minutes, all topics)',
      listening:'Extended listening — 3 speakers describing their lives',
      reading:'Full "My adult life" profile',
      writing:'"My life today" paragraph (150 words)',
      task:'Speed networking: 2 min each, 3 partners',
      cando:'Can describe all aspects of present adult life',
      hw:'Portfolio: write your "My Life Today" profile' },
  ]
},
{
  id:'u2', num:2, color:'#8B5CF6', label:'My Past',
  arc:'Career story → Past continuous → Used to → Present perfect (experience/recent/duration) → Narrative → Reported speech',
  lessons_count:10,
  grammar_summary:[
    {name:'Past Simple (extended)', desc:'Regular + irregular, career narrative, time expressions', ex:'"She left her job in 2019 and started her own company."', ref:'past-simple'},
    {name:'Past Continuous', desc:'Actions in progress; contrast with past simple', ex:'"I was working when she called."', ref:'past-simple'},
    {name:'Used to', desc:'Past habits and states no longer true', ex:'"I used to live in Paris but now I live in London."', ref:'past-simple'},
    {name:'Present Perfect — experience', desc:'ever/never; life experiences', ex:'"Have you ever worked abroad?"', ref:'present-perfect'},
    {name:'Present Perfect — recent/duration', desc:'just, already, yet; for/since', ex:'"I\'ve just finished. She\'s worked here for five years."', ref:'present-perfect'},
    {name:'Reported Speech (intro)', desc:'say/tell + that; tense shift', ex:'"She said (that) she was tired."', ref:'grammar-reference.html'},
  ],
  vocab_themes:['Career history verbs','Past time expressions','Narrative connectors','Reporting verbs'],
  lessons:[
    { code:'A1-11', num:1, title:'My career story — past simple review',
      grammar:'Past simple: regular + irregular review + time expressions (in 2015, after that, then)',
      pronunciation: [
        {
          point: "Past Simple '-ed' Endings",
          explain: "The suffix '-ed' can be pronounced in three different ways: /t/, /d/, or /ɪd/.",
          examples: [
            { pattern: "worked", ipa: "/wɜːkt/", word: "worked" },
            { pattern: "played", ipa: "/pleɪd/", word: "played" },
            { pattern: "started", ipa: "/ˈstɑː.tɪd/", word: "started" }
          ],
          extension: "Use /ɪd/ only when the base verb ends in 't' or 'd'. For most others, it's just a quick /t/ or /d/ sound.",
          visual: "⌚"
        }
      ],
      vocab: ['career','promotion','colleague'],
      verbs:['study','work','move','change','leave','join','start','become'],
      adj:['different','new','old'],
      speaking:'Tell your career story in 3 minutes to a partner',
      listening:'A career biography',
      reading:'A short professional biography',
      writing:'6-sentence career history',
      task:'Career timeline: draw and present your career path',
      cando:'Can narrate a basic career history in past simple',
      hw:'Write your career history as a timeline with sentences' },
    { code:'A1-12', num:2, title:'What were you doing? — past continuous',
      grammar:'Past continuous: was/were + -ing; contrast with past simple (while, when)',
      pronunciation: [
        {
          point: "Weak forms of 'was' and 'were'",
          explain: "In sentences, these auxiliary verbs are usually unstressed and sound weak.",
          examples: [
            { pattern: "I was", ipa: "/aɪ wəz/", word: "I was working" },
            { pattern: "They were", ipa: "/ðeɪ wə/", word: "They were talking" }
          ],
          extension: "Instead of saying 'WAZ' or 'WERE' strongly, use the schwa sound /ə/ to sound more natural.",
          visual: "☁️"
        }
      ],
      vocab: ['while','when','at that moment','suddenly'],
      verbs:['happen','continue','stop','sit','stand','carry'],
      adj:['surprised','worried'],
      speaking:'Tell a "when it happened" story using both tenses',
      listening:'An eyewitness account using both tenses',
      reading:'A short news-style account',
      writing:'3 sentences: "I was ___ when ___"',
      task:'Alibi game: where were you, what were you doing?',
      cando:'Can use past continuous for an ongoing past action',
      hw:'Write about what you were doing yesterday at specific times' },
    { code:'A1-13', num:3, title:'I used to… — past habits and states',
      grammar:'Used to + infinitive for past habits and states no longer true',
      pronunciation: [
        {
          point: "The 'used to' Liaison",
          explain: "The 'd' in 'used' and the 't' in 'to' blend into a single /tu/ sound.",
          examples: [
            { pattern: "used to", ipa: "/ˈjuːs.tə/", word: "I used to live..." }
          ],
          tip: "It sounds like 'yoos-ta'.",
          visual: "🔗"
        }
      ],
      vocab: ['anymore','not anymore','in the past','these days','now'],
      verbs:['used to + any verb'],
      adj:['different','similar'],
      speaking:'Tell a partner 3 things you used to do but don\'t anymore',
      listening:'People comparing past and present habits',
      reading:'A "My life before and after" article',
      writing:'5 "used to" sentences comparing past and present life',
      task:'Before and after: draw a timeline and present',
      cando:'Can describe past habits using "used to"',
      hw:'Write a paragraph: "My life before and now"' },
    { code:'A1-14', num:4, title:'Have you ever…? — life experiences',
      grammar:'Present perfect: have/has + past participle + ever/never for experience',
      pronunciation: [
        {
          point: "Been vs Gone",
          explain: "Differentiate between these two participles in connected speech.",
          examples: [
            { pattern: "been", ipa: "/biːn/", word: "I've been to Paris" },
            { pattern: "gone", ipa: "/ɡɒn/", word: "He's gone to Paris" }
          ],
          extension: "'Been' implies a return, while 'Gone' implies the person is still there. Pronunciation is clear: /iː/ vs /ɒ/.",
          visual: "🛫↔️🛬"
        }
      ],
      vocab: ['ever','never','once','twice','many times'],
      verbs:['visit','travel','try','meet','see','eat','do'],
      adj:['amazing','fantastic','terrible','interesting'],
      speaking:'Ask a partner 5 "Have you ever…?" questions',
      listening:'An interview about life experiences',
      reading:'A "bucket list" article',
      writing:'5 sentences: "I have / have never ___"',
      task:'"Have you ever…?" class survey — find someone who has',
      cando:'Can ask and talk about life experiences using present perfect',
      hw:'Write a "Things I have and haven\'t done" list with sentences' },
    { code:'A1-15', num:5, title:'I have just… — recent events',
      grammar:'Present perfect: just, already, yet — meaning and position',
      vocab: ['just','already','yet','recently','this week'],
      verbs:['finish','start','hear','arrive','send'],
      adj:['recent'],
      speaking:'Give 3 "just/already" updates to a partner',
      listening:'A series of short updates ("I\'ve just heard…")',
      reading:'A news update text with just/already/yet',
      writing:'5 sentences using just, already and yet',
      task:'Office updates game: report news using just/already/yet',
      cando:'Can report recent events using just, already and yet',
      hw:'Write a "news update" paragraph about your week' },
    { code:'A1-16', num:6, title:'Since when? For how long? — duration',
      grammar:'Present perfect: for + period, since + point in time; How long have you…?',
      vocab: ['for','since','how long','a week','a year','last month'],
      verbs:['live','work','study','know','have'],
      adj:['long'],
      speaking:'Ask 3 partners: "How long have you worked here/lived there?"',
      listening:'People discussing how long they have lived/worked somewhere',
      reading:'A "How long have you been here?" magazine feature',
      writing:'5 sentences about duration using for and since',
      task:'Duration timeline: display your for/since facts to the class',
      cando:'Can ask and say how long something has been the case',
      hw:'Write a paragraph using for and since about your life' },
    { code:'A1-17', num:7, title:'Telling a story — narrative skills',
      grammar:'Past simple + past continuous + present perfect (mixed past narrative)',
      vocab: ['first','then','next','after that','suddenly','in the end','finally'],
      verbs:['happen','tell','show','follow','mean','seem'],
      adj:['surprised','excited','worried','disappointed'],
      speaking:'Tell a 2-minute personal story to a partner',
      listening:'A personal narrative story (3 minutes)',
      reading:'A short story with mixed past tenses',
      writing:'120-word story about a memorable event',
      task:'Story competition: most interesting true story',
      cando:'Can tell a coherent personal story in the past',
      hw:'Write a 150-word personal narrative' },
    { code:'A1-18', num:8, title:'A difficult situation — problem narration',
      grammar:'Past tenses + wish/if only (intro): "I wish I had…"',
      vocab: ['difficulty','challenge','decision','mistake','consequence','solution'],
      verbs:['try','manage','continue','stop','change','choose','build'],
      adj:['difficult','wrong','correct','important'],
      speaking:'Describe a difficult situation you faced (2 minutes)',
      listening:'Someone describing a difficult work situation',
      reading:'A problem-solution narrative',
      writing:'100-word narrative about a challenge',
      task:'Problem sharing: listen and give advice using "you should have"',
      cando:'Can narrate a difficult past situation',
      hw:'Write about a difficult situation and how you handled it' },
    { code:'A1-19', num:9, title:'Reporting what people said',
      grammar:'Reported speech: say/tell + tense shift (present → past)',
      vocab: ['say','tell','ask','explain','mention','that'],
      verbs:['say','tell','ask','explain','mention'],
      adj:[],
      speaking:'Report what a partner told you to the class',
      listening:'Reported speech examples',
      reading:'A short article with reported quotes',
      writing:'5 reported speech sentences',
      task:'Telephone message relay: report what you heard',
      cando:'Can report what someone said using basic reported speech',
      hw:'Write 5 sentences reporting a recent conversation' },
    { code:'A1-20', num:10, title:'Unit 2 Review — My past',
      grammar:'Past simple, past continuous, used to, present perfect (all uses)',
      vocab: ['ALL Unit 2 vocabulary'],
      verbs:['ALL Unit 2 verbs'],
      adj:['ALL Unit 2 adjectives'],
      speaking:'Oral: tell your "life story" so far (3 minutes)',
      listening:'Listening test: mixed past tenses (15 items)',
      reading:'A full narrative text',
      writing:'200-word biographical paragraph',
      task:'Life story presentation to a small group',
      cando:'Can narrate personal history using all past forms',
      hw:'Portfolio: write your best personal narrative' },
  ]
},
{
  id:'u3', num:3, color:'#10B981', label:'My Future & Plans',
  arc:'Going to → Will → Arrangements → First conditional → Second conditional → Comparisons → Advice → Obligations → Requests',
  lessons_count:10,
  grammar_summary:[
    {name:'Going to + will', desc:'Plans, intentions, predictions and spontaneous decisions', ex:'"I\'m going to change jobs. I think it will be difficult."', ref:'future-plans'},
    {name:'Present continuous (future)', desc:'Fixed arrangements in diary', ex:'"I\'m meeting a client on Friday."', ref:'future-plans'},
    {name:'First conditional', desc:'Real/possible future conditions', ex:'"If you work hard, you will succeed."', ref:'conditionals'},
    {name:'Second conditional (intro)', desc:'Imagined/unlikely situations', ex:'"If I had more time, I would travel."', ref:'conditionals'},
    {name:'Must / Need to / Have to', desc:'Necessity, obligation, prohibition', ex:'"You must arrive on time. You don\'t have to wear a tie."', ref:'modals'},
    {name:'Could you / Would you mind', desc:'Polite requests and offers', ex:'"Could you send me the report? Would you mind helping?"', ref:'modals'},
  ],
  vocab_themes:['Future plans vocabulary','Conditional language','Advice vocabulary','Obligation vocabulary'],
  lessons:[
    { code:'A1-21', num:1, title:'I\'m going to change — plans and intentions',
      grammar:'Going to + infinitive for intention; present continuous for fixed arrangements',
      vocab: ['plan','intention','goal','next year','soon','eventually'],
      verbs:['plan','decide','change','move','start','save','travel'],
      adj:['different','exciting','possible'],
      speaking:'Tell a partner your top 3 plans for the next 6 months',
      listening:'People discussing future plans',
      reading:'A "My goals for next year" article',
      writing:'"My plans" paragraph (5–6 sentences)',
      task:'Goal-setting workshop: share and compare plans',
      cando:'Can describe future plans and intentions using going to',
      hw:'Write your top 5 goals for the next year' },
    { code:'A1-22', num:2, title:'It will be… — predictions and decisions',
      grammar:'Will: predictions and spontaneous decisions; contrast with going to',
      vocab: ['probably','definitely','perhaps','maybe','I think'],
      verbs:['will + any verb'],
      adj:['possible','impossible','certain','necessary'],
      speaking:'Make 3 predictions about your life in 5 years',
      listening:'Someone making predictions about their future',
      reading:'A short prediction article',
      writing:'5 will sentences (predictions + spontaneous decisions)',
      task:'Future prediction game: class makes predictions',
      cando:'Can use will for predictions and spontaneous decisions',
      hw:'Write a paragraph: "My life in 10 years"' },
    { code:'A1-23', num:3, title:'What are you doing on Friday? — arrangements',
      grammar:'Present continuous for fixed future arrangements',
      vocab: ['appointment','diary','available','schedule','arrange','confirm'],
      verbs:['meet','book','cancel','miss','arrive'],
      adj:['busy','free','available'],
      speaking:'Discuss what you are doing next week with a partner',
      listening:'A diary being discussed',
      reading:'A diary for next week',
      writing:'Your schedule for next week in full sentences',
      task:'Diary clash: find a time when everyone is free',
      cando:'Can talk about fixed future arrangements',
      hw:'Write an email confirming a future appointment' },
    { code:'A1-24', num:4, title:'If you work hard… — real conditions',
      grammar:'First conditional: if + present simple + will',
      vocab: ['if','unless','when','as soon as','result','condition'],
      verbs:['will + any verb'],
      adj:['possible','necessary','important'],
      speaking:'Give 3 pieces of advice using first conditionals',
      listening:'Advice using first conditionals',
      reading:'A "success tips" article with conditionals',
      writing:'5 first conditional sentences',
      task:'Conditional advice clinic: give real advice',
      cando:'Can use first conditional for real situations',
      hw:'Write 5 first conditional sentences about career decisions' },
    { code:'A1-25', num:5, title:'What would you do? — imagined situations',
      grammar:'Second conditional (intro): if + past + would; "I would love to / If I had…"',
      vocab: ['ideal','imagine','dream','wish','would'],
      verbs:['would + any verb'],
      adj:['ideal','amazing','different'],
      speaking:'Discuss: "What would you do if you won €100,000?"',
      listening:'Someone describing their dream job',
      reading:'A "What would you do if…?" magazine feature',
      writing:'3 second conditional sentences about dreams',
      task:'Dream job pitch: if I could do any job, I would…',
      cando:'Can use second conditional for imagined situations',
      hw:'Write a paragraph about your ideal life' },
    { code:'A1-26', num:6, title:'Making decisions — comparing options',
      grammar:'Comparatives and superlatives (extended); "It is better to… / the best option is…"',
      vocab: ['option','choice','pro','con','advantage','disadvantage','worth'],
      verbs:['choose','decide','compare','prefer'],
      adj:['better','best','worse','worst','more/less + adj'],
      speaking:'Compare two career paths or cities using comparatives',
      listening:'People comparing two options',
      reading:'A pros/cons article',
      writing:'A pros and cons list as full sentences',
      task:'Decision debate: buy or rent? Remote or office?',
      cando:'Can compare options and justify a decision',
      hw:'Write a 100-word pros and cons analysis' },
    { code:'A1-27', num:7, title:'What should I do? — giving advice',
      grammar:'Should/shouldn\'t; "Why don\'t you + infinitive"; imperative for strong advice',
      vocab: ['advice','idea','suggestion','problem','solution','option'],
      verbs:['suggest','recommend','advise','try','think about'],
      adj:['good','bad','useful','important'],
      speaking:'Role-play: give advice to someone about a problem',
      listening:'A radio advice programme',
      reading:'A problem page with advice column',
      writing:'A reply to a problem page letter',
      task:'Advice circle: each person presents a problem, others advise',
      cando:'Can ask for and give advice in real adult contexts',
      hw:'Write a letter of advice to a friend with a problem' },
    { code:'A1-28', num:8, title:'I need to… — obligation and necessity',
      grammar:'Need to / must / have to — necessity; mustn\'t for prohibition',
      vocab: ['urgent','deadline','required','necessary','compulsory'],
      verbs:['need to','must','have to','mustn\'t'],
      adj:['necessary','important','urgent'],
      speaking:'Discuss: what do you need to do this week?',
      listening:'Work instructions using obligation verbs',
      reading:'A workplace rules document',
      writing:'A list of 5 things you must do this week',
      task:'Work priorities task: rank what must be done today',
      cando:'Can express obligation and necessity using modal verbs',
      hw:'Write a to-do list with modal verbs for each item' },
    { code:'A1-29', num:9, title:'Making requests and offers',
      grammar:'Could you / Would you mind -ing / Shall I… / Would you like me to…',
      vocab: ['request','offer','favour','appreciate','mind','wonder'],
      verbs:['could','would','shall'],
      adj:['polite','formal','informal'],
      speaking:'Practise 3 polite requests with a partner',
      listening:'Formal and informal request dialogues',
      reading:'A series of emails making requests',
      writing:'A formal email with 2 polite requests',
      task:'Office role-play: chain of requests at work',
      cando:'Can make and respond to polite requests',
      hw:'Write a formal email making 3 polite requests' },
    { code:'A1-30', num:10, title:'Unit 3 Review — My future',
      grammar:'Going to, will, present continuous (future), first + second conditional, should, must',
      vocab: ['ALL Unit 3 vocabulary'],
      verbs:['ALL Unit 3 verbs'],
      adj:['ALL Unit 3 adjectives'],
      speaking:'Oral: describe future plans and give someone advice (3 min)',
      listening:'Listening test: future language (15 items)',
      reading:'A "My plans for the future" article',
      writing:'"My future plans" essay (200 words)',
      task:'Future planning simulation: life at 50',
      cando:'Can discuss the future using all A1 future structures',
      hw:'Portfolio: write "My plans for the next 5 years"' },
  ]
},
{
  id:'u4', num:4, color:'#F59E0B', label:'My World',
  arc:'Personality → Relative clauses → Discussion skills → Indirect questions → Opinions → Culture → Social invitations → Phone English → Email writing',
  lessons_count:10,
  grammar_summary:[
    {name:'Adjective + preposition', desc:'good at, bad at, interested in, worried about, etc.', ex:'"She is really good at dealing with clients."', ref:'grammar-reference.html'},
    {name:'Defining relative clauses', desc:'who, which/that, where', ex:'"The person who manages the team is very experienced."', ref:'grammar-reference.html'},
    {name:'Question tags', desc:'Positive → negative; negative → positive', ex:'"She\'s your boss, isn\'t she?"', ref:'grammar-reference.html'},
    {name:'Indirect questions', desc:'Polite enquiry with statement word order', ex:'"Could you tell me where the meeting room is?"', ref:'grammar-reference.html'},
    {name:'Opinion phrases', desc:'I think/believe/feel that + clause', ex:'"In my opinion, remote working is more productive."', ref:'grammar-reference.html'},
  ],
  vocab_themes:['Personality adjectives','Relative pronouns','Agreement phrases','Opinion language','Cultural vocabulary','Email register'],
  lessons:[
    { code:'A1-31', num:1, title:'Describing people — personality in depth',
      grammar:'Adjective + preposition: good at, bad at, interested in, worried about',
      vocab: ['reliable','organised','ambitious','creative','sensitive','tolerant','stubborn','generous'],
      verbs:['seem','appear','become'],
      adj:['reliable','organised','ambitious','creative','confident','friendly','honest','patient'],
      speaking:'Describe 3 people you know using 3 adjectives each',
      listening:'Descriptions of colleagues',
      reading:'A character sketch',
      writing:'100-word character description',
      task:'Ideal colleague: build a profile together',
      cando:'Can describe personality with adjectives and prepositions',
      hw:'Write a description of your ideal manager' },
    { code:'A1-32', num:2, title:'The person who… — relative clauses',
      grammar:'Defining relative clauses: who (people), which/that (things), where (places)',
      vocab: ['who','which','that','where','the one who','the place where'],
      verbs:['define','describe'],
      adj:['special','useful','important'],
      speaking:'Define 5 words using "it is something that/which…"',
      listening:'Relative clauses in descriptions',
      reading:'A text rich in relative clauses',
      writing:'5 sentences with relative clauses',
      task:'Definition game: describe a word using a relative clause',
      cando:'Can use defining relative clauses to describe people and things',
      hw:'Write 5 descriptions using relative clauses' },
    { code:'A1-33', num:3, title:'Agreeing and discussing — question tags',
      grammar:'Question tags: positive statement → negative tag; negative → positive',
      vocab: ['exactly','absolutely','I agree','that\'s true','isn\'t it','don\'t you'],
      verbs:['agree','disagree','think'],
      adj:['right','wrong'],
      speaking:'Practise agreeing and using tags with a partner',
      listening:'Natural conversation with question tags',
      reading:'A dialogue with agreement markers',
      writing:'5 sentences with appropriate question tags',
      task:'Discussion: agree or disagree with 5 statements',
      cando:'Can use question tags in natural conversation',
      hw:'Write a dialogue that includes 4 question tags' },
    { code:'A1-34', num:4, title:'Could you tell me…? — indirect questions',
      grammar:'Indirect questions: statement word order after question intro',
      vocab: ['I wonder if','do you know','I\'d like to know','could you tell me'],
      verbs:['wonder','know','tell','explain'],
      adj:['polite','formal'],
      speaking:'Practise 4 indirect questions in a role-play',
      listening:'Polite professional enquiries',
      reading:'A formal email with indirect questions',
      writing:'4 indirect question forms',
      task:'Information request at work or a service',
      cando:'Can use indirect questions for polite professional communication',
      hw:'Write an email using 3 indirect questions' },
    { code:'A1-35', num:5, title:'What do you think? — opinions and discussions',
      grammar:'Opinion phrases: "I think/believe that + clause"; agreeing/disagreeing',
      vocab: ['opinion','view','perspective','I think','I believe','personally','in my opinion'],
      verbs:['think','believe','feel','agree','disagree'],
      adj:['important','interesting','different','similar'],
      speaking:'Give your opinion on 3 topics to a partner',
      listening:'A short discussion with opinions',
      reading:'An opinion piece',
      writing:'100-word opinion paragraph',
      task:'Class opinion poll: vote and justify',
      cando:'Can express and justify an opinion',
      hw:'Write a 100-word opinion on a topic of your choice' },
    { code:'A1-36', num:6, title:'Talking about culture — customs and norms',
      grammar:'Present simple for general truths; "It is + adjective + to + infinitive"',
      vocab: ['custom','tradition','norm','polite','rude','different','common','respect'],
      verbs:['respect','follow','understand','compare'],
      adj:['polite','rude','normal','strange','different','common'],
      speaking:'Compare cultural norms at work with a partner',
      listening:'People comparing cultural norms',
      reading:'A short cultural comparison text',
      writing:'5 sentences about cultural norms in your country',
      task:'Cultural differences discussion: is it polite to…?',
      cando:'Can discuss cultural norms and compare customs',
      hw:'Write a short guide to your country\'s work culture' },
    { code:'A1-37', num:7, title:'A community event — social English',
      grammar:'Inviting: "Would you like to…?" / "Could you come to…?" Accepting/declining politely',
      vocab: ['invitation','celebration','RSVP','event','arrange','accept','decline'],
      verbs:['invite','celebrate','meet','join','arrange'],
      adj:['free','busy','available','sorry'],
      speaking:'Role-play: invite and respond to 3 different events',
      listening:'Social invitation conversations',
      reading:'An invitation and two replies (accept + decline)',
      writing:'A formal invitation and an informal one',
      task:'Event planning simulation: organise a work event',
      cando:'Can invite, accept and decline invitations',
      hw:'Write a formal invitation and a polite decline' },
    { code:'A1-38', num:8, title:'On the phone — telephone English',
      grammar:'Formal telephone phrases; modal verbs for politeness (could, would)',
      vocab: ['hold on','put through','leave a message','call back','available','speaking'],
      verbs:['call','phone','hold','put through','leave','call back'],
      adj:['available','busy','urgent'],
      speaking:'Role-play: 3 different phone situations',
      listening:'3 telephone conversations',
      reading:'Phone message scripts',
      writing:'A phone message from dictation',
      task:'Phone relay: message passed through 3 people',
      cando:'Can make and receive professional phone calls',
      hw:'Write a script for a professional phone call' },
    { code:'A1-39', num:9, title:'Writing an email — formal and informal',
      grammar:'Formal vs informal register; tenses in emails (present + past + future)',
      vocab: ['subject','salutation','closing','attached','regarding','sincerely','kind regards'],
      verbs:['write','reply','attach','send','thank'],
      adj:['formal','informal','polite'],
      speaking:'Discuss: what makes an email professional?',
      listening:'An email being read aloud',
      reading:'Formal vs informal emails — compare',
      writing:'A formal and informal version of the same email',
      task:'Email correction challenge: fix 6 register errors',
      cando:'Can write a simple formal and informal email',
      hw:'Write a formal email and an informal one on the same topic' },
    { code:'A1-40', num:10, title:'Unit 4 Review — Relationships and communication',
      grammar:'Relative clauses, question tags, indirect questions, opinion phrases, modal verbs',
      vocab: ['ALL Unit 4 vocabulary'],
      verbs:['ALL Unit 4 verbs'],
      adj:['ALL Unit 4 adjectives'],
      speaking:'Role-play simulation: 3 workplace communication scenarios',
      listening:'Extended listening: social and professional dialogues',
      reading:'A full social/professional text',
      writing:'150-word professional email',
      task:'Communication challenge: all Unit 4 skills in one task',
      cando:'Can communicate naturally in social and professional adult contexts',
      hw:'Portfolio: best email + description' },
  ]
},
{
  id:'u5', num:5, color:'#EC4899', label:'Mastery & Extension',
  arc:'Discussion → Fluency → Vocabulary building → Pronunciation → Reading strategies → Writing → A2 preview → Revision → Assessment',
  lessons_count:10,
  grammar_summary:[
    {name:'Mixed A1 grammar in fluency', desc:'All structures used naturally without being the focus', ex:'Extended conversation on real topics'},
    {name:'Collocations: do/make/have/take', desc:'Common fixed verb+noun combinations', ex:'"Make a decision. Do your homework. Take notes."'},
    {name:'Word stress & sentence stress', desc:'Correct stress patterns for intelligibility', ex:'"I WORK in a HOSpital" (content words stressed)'},
    {name:'Discourse connectors', desc:'Firstly, also, however, for example, in conclusion', ex:'"However, there are some disadvantages."'},
  ],
  vocab_themes:['Conversation strategies','Word families','Collocations','Academic preview vocabulary'],
  lessons:[
    { code:'A1-41', num:1, title:'My opinions on the world — discussion topics',
      grammar:'Mixed A1 grammar in discussion; because + connectors: however, so, but',
      vocab: ['environment','relationship','health','opinion','reason','because'],
      verbs:['discuss','debate','argue','agree','disagree','think'],
      adj:['important','interesting','difficult','necessary'],
      speaking:'Discuss 2 topics using opinion language',
      listening:'A short radio discussion (3 speakers)',
      reading:'A short opinion article',
      writing:'100-word opinion paragraph on a topic',
      task:'Class debate on a simple real-world topic',
      cando:'Can discuss real-world topics at A1 with simple opinions',
      hw:'Write a 120-word opinion on a topic you care about' },
    { code:'A1-42', num:2, title:'Real conversations — fluency practice',
      grammar:'Review of all A1 grammar through fluency tasks',
      vocab: ['well','actually','you know','I mean','kind of','sort of','by the way'],
      verbs:['ALL A1 verbs in natural speech'],
      adj:['ALL A1 adjectives in natural speech'],
      speaking:'Extended conversation: 5 minutes on a topic',
      listening:'Authentic short conversations (TV/radio extract)',
      reading:'A full dialogue — analyse and discuss',
      writing:'Self-record a 2-minute monologue',
      task:'Partner feedback: fluency, grammar, vocabulary',
      cando:'Can maintain a short extended conversation at A1',
      hw:'Write a script and then speak without reading it' },
    { code:'A1-43', num:3, title:'Building vocabulary — word families and collocations',
      grammar:'Collocations: do + noun, make + noun, have + noun, take + noun',
      vocab: ['do homework / exercise / research','make a decision / progress / a mistake','have a meeting / lunch / time','take notes / a break / care'],
      verbs:['do','make','have','take'],
      adj:[],
      speaking:'Collocation matching game',
      listening:'Collocations in authentic short clips',
      reading:'A text — find and note collocations',
      writing:'Write 8 collocations in full sentences',
      task:'Collocation bingo',
      cando:'Can use common collocations naturally',
      hw:'Create a collocation word map for 5 key verbs' },
    { code:'A1-44', num:4, title:'Pronunciation — stress and intonation',
      grammar:'Word and sentence stress; rising vs falling intonation in questions',
      vocab: ['stress pattern','intonation','syllable','emphasis'],
      verbs:['ALL — focus on correct stress'],
      adj:['ALL — focus on correct stress'],
      speaking:'Drill: say sentences with correct stress pattern',
      listening:'Listen and mark stress; identify question intonation',
      reading:'Read sentences aloud with marked stress',
      writing:'Write stress marks on 10 words',
      task:'Pronunciation challenge: read and record',
      cando:'Can produce correct word stress in known vocabulary',
      hw:'Learn stress patterns for 20 key A1 words' },
    { code:'A1-45', num:5, title:'Reading strategies — understanding more',
      grammar:'Mixed A1 grammar in reading context',
      vocab: ['skim','scan','infer','predict','context clue','main idea','detail'],
      verbs:['read','understand','predict','infer','summarise'],
      adj:['main','key','important','unclear'],
      speaking:'Discuss: main idea vs detail in a text',
      listening:'How to read strategically',
      reading:'A text using skimming then scanning',
      writing:'A summary of a 200-word text',
      task:'Speed reading: who finds the answer first?',
      cando:'Can use skimming and scanning to read efficiently',
      hw:'Read one article at home and write a 50-word summary' },
    { code:'A1-46', num:6, title:'Writing paragraphs — structure and cohesion',
      grammar:'Discourse connectors: firstly, also, however, for example, in conclusion',
      vocab: ['firstly','also','however','for example','in conclusion','therefore','furthermore'],
      verbs:['write','structure','link','connect'],
      adj:['clear','structured','logical'],
      speaking:'Discuss: what makes a good paragraph?',
      listening:'A short structured talk',
      reading:'3 model paragraphs — identify structure',
      writing:'A structured paragraph on a given topic',
      task:'Peer editing: improve a partner\'s paragraph',
      cando:'Can write a structured paragraph with connectors',
      hw:'Write a paragraph on your favourite topic using full structure' },
    { code:'A1-47', num:7, title:'A2 preview — What\'s coming next?',
      grammar:'Past simple vs present perfect (contrast); going to vs will (contrast)',
      vocab: ['A2 preview vocabulary: conditionals, reported speech, comparisons'],
      verbs:['ALL — seen in A2 context'],
      adj:['ALL — seen in A2 context'],
      speaking:'Discuss: what do you find hardest in English?',
      listening:'A short A2-level dialogue',
      reading:'A short A2-level article',
      writing:'Your personal language learning goals',
      task:'A1 reflection: what have you learned?',
      cando:'Can identify areas to develop at A2',
      hw:'Write your 5 goals for A2' },
    { code:'A1-48', num:8, title:'Revision day — grammar',
      grammar:'ALL A1 grammar structures — error-focused revision',
      vocab: ['ALL A1 vocabulary — student choice'],
      verbs:['ALL'],
      adj:['ALL'],
      speaking:'Grammar auction game',
      listening:'Dictation: 15 A1 sentences',
      reading:'Grammar reading: identify and correct errors',
      writing:'Grammar test: all A1 structures',
      task:'Error correction relay',
      cando:'Can recognise and correct common A1 grammar errors',
      hw:'Complete a personal grammar correction log' },
    { code:'A1-49', num:9, title:'Oral assessment preparation',
      grammar:'ALL A1 grammar in spoken context',
      vocab: ['ALL A1 topics'],
      verbs:['ALL'],
      adj:['ALL'],
      speaking:'Mock oral exam: 5 minutes (introduction + topic)',
      listening:'Practice listening tasks',
      reading:'Oral exam preparation texts',
      writing:'Preparation notes',
      task:'Peer assessment using scoring rubric',
      cando:'Can complete a full A1 oral assessment task',
      hw:'Prepare and practise your oral exam speech' },
    { code:'A1-50', num:10, title:'Final assessment and reflection',
      grammar:'ALL A1 grammar',
      vocab: ['ALL A1 vocabulary'],
      verbs:['ALL'],
      adj:['ALL'],
      speaking:'A1 oral assessment: 5 minutes',
      listening:'A1 listening test (20 items)',
      reading:'A1 reading test (full text + questions)',
      writing:'A1 writing test: email + paragraph',
      task:'Portfolio review',
      cando:'Can demonstrate all A1 competencies',
      hw:'Write a reflection: "What I can do now in English"' },
  ]
}
];
